balancer ansible_host=172.18.0.3 ansible_user=root ansible_connection=ssh
web1 ansible_host=172.18.0.2 ansible_user=root ansible_connection=ssh
web2 ansible_host=172.18.0.4 ansible_user=root ansible_connection=ssh
[web]
web1
web2
